### ISSUE TITLE
Mysql issues

### ISSUE THREAD

**Issue by nemesis567** [nopSolutions/nopCommerce#5487]
Get this issue with nop 4.3, production using MySQL with azure database for mysql.

This issue happens preventing any connections from being established, thus making the website unusable. 

`
MySql.Data.MySqlClient.MySqlException (0x80004005): error connecting: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at LinqToDB.Data.DataConnection.EnsureConnection()
   at LinqToDB.Data.DataConnection.CreateCommand()
   at LinqToDB.Data.DataConnection.get_Command()
   at LinqToDB.Data.DataConnection.QueryRunner.AddParameter(DataConnection dataConnection, ICollection"1 parms, String name, SqlParameter parm)
   at LinqToDB.Data.DataConnection.QueryRunner.GetParameters(DataConnection dataConnection, IQueryContext query, PreparedQuery pq)
   at LinqToDB.Data.DataConnection.QueryRunner.SetQuery()
   at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean clearQueryHints)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper"1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext()
   at System.Collections.Generic.List"1..ctor(IEnumerable"1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable"1 source)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func"2 factory)
   at Nop.Core.Caching.MemoryCacheManager.Get[T](CacheKey key, Func"1 acquire)
   at Nop.Services.Common.GenericAttributeService.GetAttribute[TPropType](BaseEntity entity, String key, Int32 storeId, TPropType defaultValue) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Common\GenericAttributeService.cs:line 210
   at Nop.Web.Framework.WebWorkContext.get_WorkingLanguage() in C:\andrei\nop_sources\src\Presentation\Nop.Web.Framework\WebWorkContext.cs:line 388
   at Nop.Web.Framework.Globalization.CultureMiddleware.SetWorkingCulture(IWebHelper webHelper, IWorkContext workContext) in C:\andrei\nop_sources\src\Presentation\Nop.Web.Framework\Globalization\CultureMiddleware.cs:line 60
   at Nop.Web.Framework.Globalization.CultureMiddleware.Invoke(HttpContext context, IWebHelper webHelper, IWorkContext workContext) in C:\andrei\nop_sources\src\Presentation\Nop.Web.Framework\Globalization\CultureMiddleware.cs:line 79
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 53
   at Nop.Services.Common.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\andrei\nop_sources\src\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 50
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
`

I get this issue, preventing any SQL request from happening. It apparently starts with this:

`
Mar 02 04:55:34 bb dotnet[17856]: System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
                                   ---> System.Net.Sockets.SocketException (32): Broken pipe
                                     at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                                     --- End of inner exception stack trace ---
                                     at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                                     at System.Net.Security.SslStream.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory"1 buffer)
                                     at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory"1 buffer)
                                     at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
                                     at MySql.Data.MySqlClient.TimedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
                                     at MySql.Data.MySqlClient.MySqlStream.SendPacket(MySqlPacket packet)
                                     at MySql.Data.MySqlClient.NativeDriver.ExecutePacket(MySqlPacket packetToExecute)
                                     at MySql.Data.MySqlClient.NativeDriver.Close(Boolean isOpen)
Mar 02 04:55:34 bb dotnet[17856]: Nop.Web Error: 0 :
Mar 02 04:55:32 bb dotnet[17856]: System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
                                   ---> System.Net.Sockets.SocketException (32): Broken pipe
                                     at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                                     --- End of inner exception stack trace ---
                                     at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                                     at System.Net.Security.SslStream.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory"1 buffer)
                                     at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory"1 buffer)
                                     at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
                                     at MySql.Data.MySqlClient.TimedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
                                     at MySql.Data.MySqlClient.MySqlStream.SendPacket(MySqlPacket packet)
                                     at MySql.Data.MySqlClient.NativeDriver.ExecutePacket(MySqlPacket packetToExecute)
                                     at MySql.Data.MySqlClient.NativeDriver.Close(Boolean isOpen)
Mar 02 04:55:32 bb dotnet[17856]: Nop.Web Error: 0 :
Mar 02 04:55:32 bb testsitenopcommerce[17856]:       Request starting HTTP/1.1 POST http://testsitellc.com/scheduletask/runtask application/x-www-form-urlencoded 69
`
This represents resource usage after it starts first pipe out:
https://i.ibb.co/7NsQTnW/image.png
Will provide more information as needed.

**Comment by untiedshoes** [comment]
Try adding this to your connection string: Connection Timeout=300;Min Pool Size=0;Max Pool Size=2024;Pooling=true

Your connections aren't being closed, and you end up with thread starvation.

**Comment by nemesis567** [comment]
Question is, why are they not being closed?

**Comment by nemesis567** [comment]
Ok after looking at the MySQL database provider class inside Nop I figured there is a problem, which is the values for the connection string regarding timeout, poolsize and whatever else are ignored, is this correct:

`/// <summary>
        /// Build the connection string
        /// </summary>
        /// <param name="nopConnectionString">Connection string info</param>
        /// <returns>Connection string</returns>
        public virtual string BuildConnectionString(INopConnectionStringInfo nopConnectionString)
        {
            if (nopConnectionString is null)
                throw new ArgumentNullException(nameof(nopConnectionString));

            if (nopConnectionString.IntegratedSecurity)
                throw new NopException("Data provider supports connection only with login and password");

            var builder = new MySqlConnectionStringBuilder
            {
                Server = nopConnectionString.ServerName,
                //Cast DatabaseName to lowercase to avoid case-sensitivity problems
                Database = nopConnectionString.DatabaseName.ToLower(),
                AllowUserVariables = true,
                UserID = nopConnectionString.Username,
                Password = nopConnectionString.Password,
            };

            return builder.ConnectionString;
        }`

**Comment by exileDev** [comment]
@nemesis567 I guess we already fixed it. Please, check this work item with linked commit: #5004.

**Comment by nemesis567** [comment]
Shouldn't that only cause issues when the application is started as that's only used during the initial migrations part?

**Comment by untiedshoes** [comment]
> Shouldn't that only cause issues when the application is started as that's only used during the initial migrations part?
> 
> Also when this spike in connections happened, the errors started happening at around 100 active connections and the MySQL server allows up to 600, which is also weird. Is there an internal pool size? How to change that?

Agreed, this 'fix' never resolved max pool issues we had with a 4.30 site running SQL server. Granted, a lot of those issues came down to the lack of asynchronous methods, which have now been added to 4.40... but, I'm still getting those timeout errors with a default, out of the box 4.40. I can manually increase the number of max connections via the querystring, but at the expense of very slow response times.

**Comment by nemesis567** [comment]
So what options do we have? Since server resources are barely used this is irrelevant.

If I switch to MSSQL will it resolve any issue at all?

Do I need to run multiple nopCommerce sites instanced with the same DB behind a load balancer?? This would also mean switching local file system with Azure storage or whatever.

What would you suggest because this is affecting a production site and causing massive expense.

**Comment by exileDev** [comment]
@nemesis567 Also, MigrationManager takes part in the entity mapping, but due to the implementation of IVersionLoader, it makes a lot of DB-requests that may cause overflow a pool.

**Comment by nemesis567** [comment]
Thank you I will be implementing that commit and deploy to see if we have improvements.

**Comment by exileDev** [comment]
Now I close this issue. We can reopen if this happens again.

**Comment by kunaljain90** [comment]
I am struggling with similar issue. I have a complex multi store setup and it's not sustainable due to this issue. May I know the fix for it? It is causing a massive breakdown at the moment in production

**Comment by nemesis567** [comment]
Applying the commit to 4.3 fixed the major issue, adding a few of 4.4 commits related to async methods over sync also improved performance, store as been running consistently afterwards AFAIK.
